#include "argument/a12.h"
#include "circuit/func.h"
#include "circuit/flappybird/dqn_env_gadget.h"

#include <fstream>
#include <sstream>
#include "yas/tests/base/externals/nlohmann_json.hpp"

namespace clink::flappybird {

/**
 * Read a CSV file of fixed-point integers into a 2D vector of Fr.
 * Each row in the CSV becomes a row in the result.
 * Values are already in fixed-point format (value * 2^24).
 */
inline std::vector<std::vector<Fr>> ReadWeightCsv(
    std::string const& filepath) {
  std::ifstream file(filepath);
  CHECK(file.is_open(), "Cannot open weight file: " << filepath);

  std::vector<std::vector<Fr>> result;
  std::string line;
  while (std::getline(file, line)) {
    if (line.empty()) continue;
    std::vector<Fr> row;
    std::istringstream stream(line);
    std::string token;
    while (std::getline(stream, token, ',')) {
      int64_t value = std::stoll(token);
      row.push_back(Fr(value));
    }
    result.push_back(std::move(row));
  }
  return result;
}

/**
 * Transpose a 2D weight matrix: [rows][cols] -> [cols][rows]
 */
inline std::vector<std::vector<Fr>> TransposeWeights(
    std::vector<std::vector<Fr>> const& matrix) {
  if (matrix.empty()) return {};
  size_t rows = matrix.size();
  size_t cols = matrix[0].size();
  std::vector<std::vector<Fr>> transposed(cols, std::vector<Fr>(rows));
  for (size_t r = 0; r < rows; ++r) {
    for (size_t c = 0; c < cols; ++c) {
      transposed[c][r] = matrix[r][c];
    }
  }
  return transposed;
}

struct FlappyBird {
  struct Para {
    // Conv1: Conv2d(4, 32, kernel=8, stride=4)
    // Shape: [32][4*8*8 + 1] = [32][257]
    std::vector<std::vector<Fr>> conv1;

    // Conv2: Conv2d(32, 64, kernel=4, stride=2)
    // Shape: [64][32*4*4 + 1] = [64][513]
    std::vector<std::vector<Fr>> conv2;

    // Conv3: Conv2d(64, 64, kernel=3, stride=1)
    // Shape: [64][64*3*3 + 1] = [64][577]
    std::vector<std::vector<Fr>> conv3;

    // FC1: Linear(3136, 512)
    // Shape: [3136 + 1][512] = [3137][512]
    std::vector<std::vector<Fr>> fc1;

    // FC2: Linear(512, 2)
    // Shape: [512 + 1][2] = [513][2]
    std::vector<std::vector<Fr>> fc2;
  };

  /**
   * Load CNN model parameters from CSV files.
   * CSV files are generated by extract_flappybird_weights.py.
   * Values are stored as fixed-point integers (value * 2^24).
   *
   * @param data_dir  Directory containing the CSV files
   *                  (default: "data/flappybird" relative to project root)
   */
  static void LoadPara(Para& para,
                       std::string const& data_dir = "") {
    Tick tick(__FN__);

    // Auto-detect data directory: try "data/flappybird" then "../data/flappybird"
    std::string resolved_dir = data_dir;
    if (resolved_dir.empty()) {
      std::ifstream test_file("data/flappybird/conv1_weights.csv");
      if (test_file.is_open()) {
        resolved_dir = "data/flappybird";
      } else {
        std::ifstream test_file2("../data/flappybird/conv1_weights.csv");
        CHECK(test_file2.is_open(),
              "Cannot find data directory. Run from project root or pod_dummy/");
        resolved_dir = "../data/flappybird";
      }
      std::cout << "Using data directory: " << resolved_dir << "\n";
    }

    para.conv1 = ReadWeightCsv(resolved_dir + "/conv1_weights.csv");
    CHECK(para.conv1.size() == 32 && para.conv1[0].size() == 257,
          "conv1 shape mismatch: expected [32][257], got ["
              << para.conv1.size() << "][" << para.conv1[0].size() << "]");

    para.conv2 = ReadWeightCsv(resolved_dir + "/conv2_weights.csv");
    CHECK(para.conv2.size() == 64 && para.conv2[0].size() == 513,
          "conv2 shape mismatch: expected [64][513], got ["
              << para.conv2.size() << "][" << para.conv2[0].size() << "]");

    para.conv3 = ReadWeightCsv(resolved_dir + "/conv3_weights.csv");
    CHECK(para.conv3.size() == 64 && para.conv3[0].size() == 577,
          "conv3 shape mismatch: expected [64][577], got ["
              << para.conv3.size() << "][" << para.conv3[0].size() << "]");

    // fc1 and fc2 CSV files: [out_dim][in_dim+1] (same as conv layers)
    para.fc1 = ReadWeightCsv(resolved_dir + "/fc1_weights.csv");
    CHECK(para.fc1.size() == 512 && para.fc1[0].size() == 3137,
          "fc1 shape mismatch: expected [512][3137], got ["
              << para.fc1.size() << "][" << para.fc1[0].size() << "]");

    para.fc2 = ReadWeightCsv(resolved_dir + "/fc2_weights.csv");
    CHECK(para.fc2.size() == 2 && para.fc2[0].size() == 513,
          "fc2 shape mismatch: expected [2][513], got ["
              << para.fc2.size() << "][" << para.fc2[0].size() << "]");

    std::cout << "Loaded CNN weights: conv1[32x257] conv2[64x513] "
              << "conv3[64x577] fc1[512x3137] fc2[2x513]\n";
  }
};

/**
 * Performance statistics for IteratedFunctionProof
 */
struct IteratedFunctionProofStats {
  size_t max_steps;
  size_t num_instances;
  size_t num_constraints;
  size_t num_vars;
  double trajectory_gen_ms;
  double matrix_transpose_ms;
  double compute_com_ms;
  double prove_ms;
  double verify_ms;
  double total_ms;
  size_t proof_fr_size;
  size_t proof_g1_size;
  bool verify_success;
  double peak_memory_mb;
  size_t com_g1_count;
  size_t com_serialized_size;
  size_t proof_serialized_size;
  size_t total_proof_size;
  double prove_total_ms;
  double verify_total_ms;

  void print() const {
    std::cout << "\n========== Performance Statistics ==========\n";
    std::cout << "max_steps:         " << max_steps << "\n";
    std::cout << "num_instances:     " << num_instances << "\n";
    std::cout << "num_constraints:   " << num_constraints << "\n";
    std::cout << "num_vars:          " << num_vars << "\n";
    std::cout << "--------------------------------------------\n";
    std::cout << std::fixed << std::setprecision(2);
    std::cout << "trajectory_gen:    " << trajectory_gen_ms << " ms\n";
    std::cout << "matrix_transpose:  " << matrix_transpose_ms << " ms\n";
    std::cout << "compute_com:       " << compute_com_ms << " ms\n";
    std::cout << "prove:             " << prove_ms << " ms\n";
    std::cout << "verify:            " << verify_ms << " ms\n";
    std::cout << "total:             " << total_ms << " ms\n";
    std::cout << "--------------------------------------------\n";
    std::cout << "prove_total:       " << prove_total_ms << " ms (trajectory_gen + compute_com + prove)\n";
    std::cout << "verify_total:      " << verify_total_ms << " ms\n";
    std::cout << "--------------------------------------------\n";
    std::cout << "com_g1_count:      " << com_g1_count << "\n";
    std::cout << "com_size:          " << com_serialized_size << " bytes\n";
    std::cout << "proof_fr_size:     " << proof_fr_size << "\n";
    std::cout << "proof_g1_size:     " << proof_g1_size << "\n";
    std::cout << "proof_size:        " << proof_serialized_size << " bytes\n";
    std::cout << "total_proof_size:  " << total_proof_size << " bytes (com + proof)\n";
    std::cout << "verify_success:    " << (verify_success ? "true" : "false") << "\n";
    std::cout << "peak_memory:       " << peak_memory_mb << " MB\n";
    std::cout << "============================================\n\n";
  }
};

/**
 * Generate a dummy 84x84x4 image input for the CNN.
 * In a real scenario, this would come from the game renderer.
 * For circuit testing, we use a deterministic image based on the state.
 */
inline std::vector<Fr> GenerateDummyImage(std::vector<Fr> const& state) {
  circuit::fp::RationalConst<8, 24> rc;
  constexpr size_t IMG_SIZE = 4 * 84 * 84;  // 28224

  int64_t bird_y = (state[0] / rc.kFrN).getInt64();
  int64_t pipe_x = (state[2] / rc.kFrN).getInt64();
  int64_t gap_y = (state[3] / rc.kFrN).getInt64();

  std::vector<Fr> image(IMG_SIZE, Fr(0));

  // Create a simple deterministic image:
  // Channel 0: bird position (white pixel at bird location)
  // Channel 1: pipe position (vertical bars)
  // Channel 2-3: copies shifted by 1 frame (for frame stacking)
  for (size_t c = 0; c < 4; ++c) {
    for (size_t h = 0; h < 84; ++h) {
      for (size_t w = 0; w < 84; ++w) {
        size_t idx = c * 84 * 84 + h * 84 + w;
        int scaled_h = static_cast<int>(h * 512.0 / 84.0);
        int scaled_w = static_cast<int>(w * 288.0 / 84.0);

        // Bird: small rectangle around bird position
        int bird_screen_y = static_cast<int>(bird_y) + static_cast<int>(c);
        if (std::abs(scaled_h - bird_screen_y) < 12 &&
            std::abs(scaled_w - 57) < 17) {
          image[idx] = rc.kFrN;  // 1.0 in fixed-point
        }
        // Pipe: vertical bars at pipe_x
        int pipe_screen_x = static_cast<int>(pipe_x) + static_cast<int>(c) * 4;
        if (std::abs(scaled_w - pipe_screen_x) < 26) {
          int upper_pipe_bottom = static_cast<int>(gap_y) - 50;
          int lower_pipe_top = static_cast<int>(gap_y) + 50;
          if (scaled_h < upper_pipe_bottom || scaled_h > lower_pipe_top) {
            image[idx] = rc.kFrN;  // 1.0 in fixed-point
          }
        }
      }
    }
  }
  return image;
}

/**
 * Helper: Allocate and assign weight variables on protoboard.
 * Para format: para[out_dim][in_dim+1] (each row = one output neuron's weights + bias)
 * Flat format: row-major, flat[oc * (in_dim+1) + i] = para[oc][i]
 * This matches PyTorch's nn.Linear(in, out) weight layout [out, in] + bias.
 */
inline void AllocateAndAssignWeights(
    libsnark::protoboard<Fr>& pb,
    libsnark::pb_variable_array<Fr>& weight_vars,
    std::vector<std::vector<Fr>> const& para_weights,
    const std::string& prefix) {
  size_t out_dim = para_weights.size();
  size_t in_plus_bias = para_weights[0].size();
  size_t total = out_dim * in_plus_bias;
  weight_vars.allocate(pb, total, prefix);
  for (size_t oc = 0; oc < out_dim; ++oc) {
    for (size_t i = 0; i < in_plus_bias; ++i) {
      pb.val(weight_vars[oc * in_plus_bias + i]) = para_weights[oc][i];
    }
  }
}

/**
 * Helper: Assign weight values from Para to pre-allocated weight variables.
 * Para format: para[out_dim][in_dim+1] (row-major, directly flattened)
 */
inline void AssignWeights(
    libsnark::protoboard<Fr>& pb,
    libsnark::pb_variable_array<Fr> const& weight_vars,
    std::vector<std::vector<Fr>> const& para_weights) {
  size_t out_dim = para_weights.size();
  size_t in_plus_bias = para_weights[0].size();
  for (size_t oc = 0; oc < out_dim; ++oc) {
    for (size_t i = 0; i < in_plus_bias; ++i) {
      pb.val(weight_vars[oc * in_plus_bias + i]) = para_weights[oc][i];
    }
  }
}

/**
 * Helper struct holding all allocated variables for DqnEnvGadget.
 */
struct DqnEnvGadgetVars {
  libsnark::pb_variable_array<Fr> in_state;
  libsnark::pb_variable_array<Fr> prev_images;
  libsnark::pb_variable<Fr> next_gap_y;
  libsnark::pb_variable_array<Fr> conv1_weights;
  libsnark::pb_variable_array<Fr> conv2_weights;
  libsnark::pb_variable_array<Fr> conv3_weights;
  libsnark::pb_variable_array<Fr> fc1_weights;
  libsnark::pb_variable_array<Fr> fc2_weights;
};

/**
 * Helper: Create DqnEnvGadget with all input variables allocated on protoboard.
 */
inline std::unique_ptr<circuit::flappybird::DqnEnvGadget<8, 24>> CreateDqnEnvGadget(
    libsnark::protoboard<Fr>& pb,
    DqnEnvGadgetVars& vars,
    const std::string& prefix) {
  using Gadget = circuit::flappybird::DqnEnvGadget<8, 24>;
  constexpr int STATE_SIZE = Gadget::STATE_SIZE;
  constexpr int PREV_IMAGES_SIZE = Gadget::NUM_PREV_FRAMES * Gadget::IMAGE_SIZE_84;

  vars.in_state.allocate(pb, STATE_SIZE, prefix + " in_state");
  vars.prev_images.allocate(pb, PREV_IMAGES_SIZE, prefix + " prev_images");
  vars.next_gap_y.allocate(pb, prefix + " next_gap_y");

  using DqnG = circuit::flappybird::DqnGadget<8, 24>;
  vars.conv1_weights.allocate(pb, DqnG::CONV1_WEIGHT_SIZE, prefix + " conv1_w");
  vars.conv2_weights.allocate(pb, DqnG::CONV2_WEIGHT_SIZE, prefix + " conv2_w");
  vars.conv3_weights.allocate(pb, DqnG::CONV3_WEIGHT_SIZE, prefix + " conv3_w");
  vars.fc1_weights.allocate(pb, (DqnG::FC1_IN + 1) * DqnG::FC1_OUT, prefix + " fc1_w");
  vars.fc2_weights.allocate(pb, (DqnG::FC2_IN + 1) * DqnG::FC2_OUT, prefix + " fc2_w");

  return std::make_unique<Gadget>(
      pb, vars.in_state, vars.prev_images, vars.next_gap_y,
      vars.conv1_weights, vars.conv2_weights, vars.conv3_weights,
      vars.fc1_weights, vars.fc2_weights, prefix);
}

/**
 * Save FlatMatrix to binary file.
 * Format: [rows:int64_t][cols:int64_t][data:Fr*rows*cols]
 */
inline void SaveFlatMatrix(const FlatMatrix& mat, const std::string& filepath) {
  std::ofstream ofs(filepath, std::ios::binary);
  CHECK(ofs.is_open(), "Cannot open file for writing: " << filepath);
  int64_t rows = mat.rows();
  int64_t cols = mat.cols();
  ofs.write(reinterpret_cast<const char*>(&rows), sizeof(rows));
  ofs.write(reinterpret_cast<const char*>(&cols), sizeof(cols));
  for (int64_t i = 0; i < rows; ++i) {
    for (int64_t j = 0; j < cols; ++j) {
      Fr val = mat(i, j);
      ofs.write(reinterpret_cast<const char*>(&val), sizeof(Fr));
    }
  }
  std::cout << "Saved FlatMatrix (" << rows << "x" << cols << ") to " << filepath << "\n";
}

/**
 * Load FlatMatrix from binary file.
 */
inline FlatMatrix LoadFlatMatrix(const std::string& filepath) {
  std::ifstream ifs(filepath, std::ios::binary);
  CHECK(ifs.is_open(), "Cannot open file for reading: " << filepath);
  int64_t rows, cols;
  ifs.read(reinterpret_cast<char*>(&rows), sizeof(rows));
  ifs.read(reinterpret_cast<char*>(&cols), sizeof(cols));
  FlatMatrix mat(rows, cols);
  for (int64_t i = 0; i < rows; ++i) {
    for (int64_t j = 0; j < cols; ++j) {
      Fr val;
      ifs.read(reinterpret_cast<char*>(&val), sizeof(Fr));
      mat(i, j) = val;
    }
  }
  std::cout << "Loaded FlatMatrix (" << rows << "x" << cols << ") from " << filepath << "\n";
  return mat;
}

/**
 * Save copy ranges to file.
 */
inline void SaveCopyRanges(const std::vector<argument::CopyRange>& ranges, const std::string& filepath) {
  std::ofstream ofs(filepath, std::ios::binary);
  CHECK(ofs.is_open(), "Cannot open file for writing: " << filepath);
  size_t count = ranges.size();
  ofs.write(reinterpret_cast<const char*>(&count), sizeof(count));
  for (const auto& r : ranges) {
    ofs.write(reinterpret_cast<const char*>(&r.l_a), sizeof(r.l_a));
    ofs.write(reinterpret_cast<const char*>(&r.l_b), sizeof(r.l_b));
    ofs.write(reinterpret_cast<const char*>(&r.l), sizeof(r.l));
  }
  std::cout << "Saved " << count << " copy ranges to " << filepath << "\n";
}

/**
 * Load copy ranges from file.
 */
inline std::vector<argument::CopyRange> LoadCopyRanges(const std::string& filepath) {
  std::ifstream ifs(filepath, std::ios::binary);
  CHECK(ifs.is_open(), "Cannot open file for reading: " << filepath);
  size_t count;
  ifs.read(reinterpret_cast<char*>(&count), sizeof(count));
  std::vector<argument::CopyRange> ranges(count);
  for (auto& r : ranges) {
    ifs.read(reinterpret_cast<char*>(&r.l_a), sizeof(r.l_a));
    ifs.read(reinterpret_cast<char*>(&r.l_b), sizeof(r.l_b));
    ifs.read(reinterpret_cast<char*>(&r.l), sizeof(r.l));
  }
  std::cout << "Loaded " << count << " copy ranges from " << filepath << "\n";
  return ranges;
}

/**
 * Phase 1: Generate trajectory only.
 * Saves flat_row_z and copy_ranges to files.
 */
inline void GenerateTrajectoryPhase(size_t max_steps,
                                    std::string const& data_dir = "",
                                    std::string const& output_dir = ".") {
  Tick tick(__FN__);
  namespace fp = circuit::fp;
  fp::RationalConst<8, 24> rc;

  FlappyBird::Para para;
  FlappyBird::LoadPara(para, data_dir);

  // Create protoboard and gadget
  libsnark::protoboard<Fr> pb;
  DqnEnvGadgetVars vars;
  auto gadget_ptr = CreateDqnEnvGadget(pb, vars, "DqnEnvGadget");
  auto& gadget = *gadget_ptr;

  SparseMatrix sparse_a, sparse_b, sparse_c;
  circuit::PreprocessSparse(pb, sparse_a, sparse_b, sparse_c);

  auto r1cs_stats = circuit::GetR1csStats(sparse_a, sparse_b, sparse_c);
  std::cout << "R1CS: " << r1cs_stats.num_constraints << " constraints, "
            << r1cs_stats.num_variables << " variables\n";

  int64_t num_variables = static_cast<int64_t>(pb.num_variables());
  int64_t num_constraints = r1cs_stats.num_constraints;

  // Get variable indices for copy constraints
  size_t in_start_idx = vars.in_state[0].index;
  size_t out_start_idx = gadget.out_state()[0].index;
  size_t prev_images_start_idx = vars.prev_images[0].index;
  size_t out_image_start_idx = gadget.out_image()[0].index;
  constexpr int IMG_84 = 84 * 84;

  // Generate trajectory
  auto traj_start = std::chrono::high_resolution_clock::now();
  int64_t total_vars = num_variables + 1;

  FlatMatrix flat_row_z(total_vars, static_cast<int64_t>(max_steps));
  size_t actual_steps = 0;

  // Assign CNN weights
  AssignWeights(pb, vars.conv1_weights, para.conv1);
  AssignWeights(pb, vars.conv2_weights, para.conv2);
  AssignWeights(pb, vars.conv3_weights, para.conv3);
  AssignWeights(pb, vars.fc1_weights, para.fc1);
  AssignWeights(pb, vars.fc2_weights, para.fc2);

  // Initial state
  std::vector<Fr> state = {
      Fr(244), Fr(0), Fr(288), Fr(140), Fr(432), Fr(160), Fr(0), Fr(0)
  };

  constexpr int PREV_IMAGES_SIZE = 3 * 84 * 84;
  std::vector<Fr> prev_images(PREV_IMAGES_SIZE, Fr(0));

  for (size_t step = 0; step < max_steps; ++step) {
    for (int i = 0; i < circuit::flappybird::EnvGadget::STATE_DIM; ++i) {
      pb.val(vars.in_state[i]) = state[i];
    }

    auto assign_prev_images = [&](int64_t i) {
      pb.val(vars.prev_images[i]) = prev_images[i];
    };
    parallel::For(static_cast<int64_t>(PREV_IMAGES_SIZE), assign_prev_images);

    int64_t next_gap_y_val = 100 + static_cast<int64_t>((step * 37 + 17) % 9) * 10;
    pb.val(vars.next_gap_y) = Fr(next_gap_y_val);

    gadget.generate_r1cs_witness();

    int64_t col_idx = static_cast<int64_t>(step);
    auto const& full_assignment = pb.full_variable_assignment();
    flat_row_z(0, col_idx) = FrOne();
    auto collect_assignment = [&](int64_t i) {
      flat_row_z(i + 1, col_idx) = full_assignment[i];
    };
    parallel::For(num_variables, collect_assignment);
    actual_steps = step + 1;

    // Read output state
    std::vector<Fr> out_state(circuit::flappybird::EnvGadget::STATE_DIM);
    for (int i = 0; i < circuit::flappybird::EnvGadget::STATE_DIM; ++i) {
      out_state[i] = pb.val(gadget.out_state()[i]);
    }

    // Update previous images
    auto const& cur_image = gadget.out_image();
    auto copy_frame0 = [&](int64_t i) { prev_images[i] = prev_images[IMG_84 + i]; };
    parallel::For(static_cast<int64_t>(IMG_84), copy_frame0);
    auto copy_frame1 = [&](int64_t i) { prev_images[IMG_84 + i] = prev_images[2 * IMG_84 + i]; };
    parallel::For(static_cast<int64_t>(IMG_84), copy_frame1);
    auto copy_new_frame = [&](int64_t i) { prev_images[2 * IMG_84 + i] = pb.val(cur_image[i]); };
    parallel::For(static_cast<int64_t>(IMG_84), copy_new_frame);

    state = out_state;

    if (step % 10 == 0) {
      std::cout << "Step " << step << " completed, memory: " 
                << misc::GetPeakMemoryByPid(getpid()) / 1024.0 << " MB\n";
    }
  }

  auto traj_end = std::chrono::high_resolution_clock::now();
  double trajectory_gen_ms = std::chrono::duration<double, std::milli>(traj_end - traj_start).count();

  std::cout << "Generated " << actual_steps << " steps in " << trajectory_gen_ms << " ms\n";

  // Build copy ranges
  constexpr int STATE_DIM = circuit::flappybird::EnvGadget::STATE_DIM;
  int64_t prev_frame0_start = static_cast<int64_t>(prev_images_start_idx);
  int64_t prev_frame1_start = static_cast<int64_t>(prev_images_start_idx + IMG_84);
  int64_t prev_frame2_start = static_cast<int64_t>(prev_images_start_idx + 2 * IMG_84);

  std::vector<argument::CopyRange> copy_ranges;
  copy_ranges.emplace_back(static_cast<int64_t>(out_start_idx), static_cast<int64_t>(in_start_idx), static_cast<int64_t>(STATE_DIM));
  copy_ranges.emplace_back(prev_frame1_start, prev_frame0_start, static_cast<int64_t>(IMG_84));
  copy_ranges.emplace_back(prev_frame2_start, prev_frame1_start, static_cast<int64_t>(IMG_84));
  copy_ranges.emplace_back(static_cast<int64_t>(out_image_start_idx), prev_frame2_start, static_cast<int64_t>(IMG_84));

  // Save to files
  SaveFlatMatrix(flat_row_z, output_dir + "/flappybird_trajectory.bin");
  SaveCopyRanges(copy_ranges, output_dir + "/flappybird_copy_ranges.bin");

  // Save metadata
  std::ofstream meta_ofs(output_dir + "/flappybird_meta.txt");
  meta_ofs << "num_constraints: " << num_constraints << "\n";
  meta_ofs << "num_variables: " << num_variables << "\n";
  meta_ofs << "num_instances: " << actual_steps << "\n";
  meta_ofs << "trajectory_gen_ms: " << trajectory_gen_ms << "\n";
  meta_ofs << "peak_memory_mb: " << misc::GetPeakMemoryByPid(getpid()) / 1024.0 << "\n";
  meta_ofs.close();

  std::cout << "\n========== Phase 1 Complete ==========\n";
  std::cout << "trajectory_gen:    " << trajectory_gen_ms << " ms\n";
  std::cout << "num_instances:     " << actual_steps << "\n";
  std::cout << "peak_memory:       " << misc::GetPeakMemoryByPid(getpid()) / 1024.0 << " MB\n";
  std::cout << "======================================\n";
}

/**
 * Phase 2: Compute commitment only.
 * Loads trajectory from file, computes and saves commitment.
 */
inline void ComputeCommitmentPhase(std::string const& input_dir = ".") {
  Tick tick(__FN__);

  // Load metadata
  int64_t num_constraints = 0, num_variables = 0, num_instances = 0;
  double trajectory_gen_ms = 0;
  {
    std::ifstream meta_ifs(input_dir + "/flappybird_meta.txt");
    std::string line;
    while (std::getline(meta_ifs, line)) {
      if (line.find("num_constraints:") != std::string::npos) {
        num_constraints = std::stoll(line.substr(line.find(":") + 1));
      } else if (line.find("num_variables:") != std::string::npos) {
        num_variables = std::stoll(line.substr(line.find(":") + 1));
      } else if (line.find("num_instances:") != std::string::npos) {
        num_instances = std::stoll(line.substr(line.find(":") + 1));
      } else if (line.find("trajectory_gen_ms:") != std::string::npos) {
        trajectory_gen_ms = std::stod(line.substr(line.find(":") + 1));
      }
    }
  }
  std::cout << "Loaded metadata: " << num_constraints << " constraints, "
            << num_variables << " variables, " << num_instances << " instances\n";

  // Load trajectory and copy ranges
  FlatMatrix flat_row_z = LoadFlatMatrix(input_dir + "/flappybird_trajectory.bin");
  std::vector<argument::CopyRange> copy_ranges = LoadCopyRanges(input_dir + "/flappybird_copy_ranges.bin");

  // Create protoboard to get sparse matrices
  libsnark::protoboard<Fr> pb;
  DqnEnvGadgetVars vars;
  auto gadget_ptr = CreateDqnEnvGadget(pb, vars, "DqnEnvGadget");
  SparseMatrix sparse_a, sparse_b, sparse_c;
  circuit::PreprocessSparse(pb, sparse_a, sparse_b, sparse_c);

  // Compute commitment
  auto com_start = std::chrono::high_resolution_clock::now();
  argument::A12::SparseProveInput prove_input(
      sparse_a, sparse_b, sparse_c, flat_row_z, copy_ranges, pc::kGetRefG1);
  argument::A12::CommitmentPub com_pub;
  argument::A12::CommitmentSec com_sec;
  argument::A12::ComputeCom(com_pub, com_sec, prove_input);
  auto com_end = std::chrono::high_resolution_clock::now();
  double compute_com_ms = std::chrono::duration<double, std::milli>(com_end - com_start).count();

  // Save commitment
  {
    yas::mem_ostream com_os;
    yas::binary_oarchive<yas::mem_ostream, YasBinF()> com_oa(com_os);
    com_oa.serialize(com_pub);
    com_oa.serialize(com_sec);
    auto buf = com_os.get_shared_buffer();
    std::ofstream ofs(input_dir + "/flappybird_commitment.bin", std::ios::binary);
    ofs.write(reinterpret_cast<const char*>(buf.data.get()), buf.size);
    std::cout << "Saved commitment (" << buf.size << " bytes) to " << input_dir << "/flappybird_commitment.bin\n";
  }

  // Update metadata
  std::ofstream meta_ofs(input_dir + "/flappybird_meta.txt", std::ios::app);
  meta_ofs << "compute_com_ms: " << compute_com_ms << "\n";
  meta_ofs << "com_g1_count: " << com_pub.com_z.size() << "\n";
  meta_ofs.close();

  std::cout << "\n========== Phase 2 Complete ==========\n";
  std::cout << "compute_com:       " << compute_com_ms << " ms\n";
  std::cout << "com_g1_count:      " << com_pub.com_z.size() << "\n";
  std::cout << "peak_memory:       " << misc::GetPeakMemoryByPid(getpid()) / 1024.0 << " MB\n";
  std::cout << "======================================\n";
}

/**
 * Phase 3: Generate proof only.
 * Loads trajectory and commitment, generates and saves proof.
 */
inline void GenerateProofPhase(std::string const& input_dir = ".") {
  Tick tick(__FN__);

  // Load metadata
  int64_t num_instances = 0;
  double trajectory_gen_ms = 0, compute_com_ms = 0;
  {
    std::ifstream meta_ifs(input_dir + "/flappybird_meta.txt");
    std::string line;
    while (std::getline(meta_ifs, line)) {
      if (line.find("num_instances:") != std::string::npos) {
        num_instances = std::stoll(line.substr(line.find(":") + 1));
      } else if (line.find("trajectory_gen_ms:") != std::string::npos) {
        trajectory_gen_ms = std::stod(line.substr(line.find(":") + 1));
      } else if (line.find("compute_com_ms:") != std::string::npos) {
        compute_com_ms = std::stod(line.substr(line.find(":") + 1));
      }
    }
  }

  // Load trajectory and copy ranges
  FlatMatrix flat_row_z = LoadFlatMatrix(input_dir + "/flappybird_trajectory.bin");
  std::vector<argument::CopyRange> copy_ranges = LoadCopyRanges(input_dir + "/flappybird_copy_ranges.bin");

  // Analyze witness matrix Z sparsity
  {
    int64_t total_rows = flat_row_z.rows();
    int64_t total_cols = flat_row_z.cols();
    int64_t total_elements = total_rows * total_cols;
    int64_t nonzero_count = 0;
    int64_t one_count = 0;
    // Count non-zero elements per column
    std::vector<int64_t> col_nnz(total_cols, 0);
    for (int64_t i = 0; i < total_rows; ++i) {
      for (int64_t j = 0; j < total_cols; ++j) {
        if (flat_row_z(i, j) != FrZero()) {
          nonzero_count++;
          col_nnz[j]++;
          if (flat_row_z(i, j) == FrOne()) one_count++;
        }
      }
    }
    double sparsity = 1.0 - static_cast<double>(nonzero_count) / total_elements;
    double dense_memory_gb = static_cast<double>(total_elements) * 32.0 / (1024.0 * 1024.0 * 1024.0);
    double sparse_memory_gb = static_cast<double>(nonzero_count) * (32 + 8) / (1024.0 * 1024.0 * 1024.0);  // Fr + col_idx

    std::cout << "\n========== Witness Matrix Z Sparsity Analysis ==========\n";
    std::cout << "dimensions:        " << total_rows << " x " << total_cols << "\n";
    std::cout << "total_elements:    " << total_elements << "\n";
    std::cout << "nonzero_count:     " << nonzero_count << "\n";
    std::cout << "one_count:         " << one_count << "\n";
    std::cout << "sparsity:          " << (sparsity * 100.0) << "%\n";
    std::cout << "dense_memory:      " << dense_memory_gb << " GB\n";
    std::cout << "sparse_memory:     " << sparse_memory_gb << " GB (estimated)\n";
    std::cout << "memory_saving:     " << (dense_memory_gb - sparse_memory_gb) << " GB\n";

    // Per-column non-zero stats
    int64_t min_col_nnz = *std::min_element(col_nnz.begin(), col_nnz.end());
    int64_t max_col_nnz = *std::max_element(col_nnz.begin(), col_nnz.end());
    double avg_col_nnz = static_cast<double>(nonzero_count) / total_cols;
    std::cout << "col_nnz_min:       " << min_col_nnz << " (" << (100.0 * min_col_nnz / total_rows) << "% of rows)\n";
    std::cout << "col_nnz_max:       " << max_col_nnz << " (" << (100.0 * max_col_nnz / total_rows) << "% of rows)\n";
    std::cout << "col_nnz_avg:       " << avg_col_nnz << " (" << (100.0 * avg_col_nnz / total_rows) << "% of rows)\n";
    std::cout << "========================================================\n\n";
  }

  // Create protoboard to get sparse matrices
  libsnark::protoboard<Fr> pb;
  DqnEnvGadgetVars vars;
  auto gadget_ptr = CreateDqnEnvGadget(pb, vars, "DqnEnvGadget");
  SparseMatrix sparse_a, sparse_b, sparse_c;
  circuit::PreprocessSparse(pb, sparse_a, sparse_b, sparse_c);

  // Load commitment
  argument::A12::CommitmentPub com_pub;
  argument::A12::CommitmentSec com_sec;
  {
    std::ifstream ifs(input_dir + "/flappybird_commitment.bin", std::ios::binary);
    ifs.seekg(0, std::ios::end);
    size_t size = ifs.tellg();
    ifs.seekg(0, std::ios::beg);
    std::vector<uint8_t> buf(size);
    ifs.read(reinterpret_cast<char*>(buf.data()), size);
    yas::mem_istream is(buf.data(), size);
    yas::binary_iarchive<yas::mem_istream, YasBinF()> ia(is);
    ia.serialize(com_pub);
    ia.serialize(com_sec);
    std::cout << "Loaded commitment from " << input_dir << "/flappybird_commitment.bin\n";
  }

  // Generate proof
  h256_t seed = misc::RandH256();
  argument::A12::SparseProveInput prove_input(
      sparse_a, sparse_b, sparse_c, flat_row_z, copy_ranges, pc::kGetRefG1);

  auto prove_start = std::chrono::high_resolution_clock::now();
  argument::A12::Proof proof;
  argument::A12::ProveIf(proof, seed, prove_input, com_pub, com_sec);
  auto prove_end = std::chrono::high_resolution_clock::now();
  double prove_ms = std::chrono::duration<double, std::milli>(prove_end - prove_start).count();

  // Save proof and seed
  {
    yas::mem_ostream proof_os;
    yas::binary_oarchive<yas::mem_ostream, YasBinF()> proof_oa(proof_os);
    proof_oa.serialize(proof);
    proof_oa.serialize(seed);
    auto buf = proof_os.get_shared_buffer();
    std::ofstream ofs(input_dir + "/flappybird_proof.bin", std::ios::binary);
    ofs.write(reinterpret_cast<const char*>(buf.data.get()), buf.size);
    std::cout << "Saved proof (" << buf.size << " bytes) to " << input_dir << "/flappybird_proof.bin\n";
  }

  // Update metadata
  std::ofstream meta_ofs(input_dir + "/flappybird_meta.txt", std::ios::app);
  meta_ofs << "prove_ms: " << prove_ms << "\n";
  meta_ofs << "prove_total_ms: " << (trajectory_gen_ms + compute_com_ms + prove_ms) << "\n";
  meta_ofs << "proof_fr_size: " << proof.FrSize() << "\n";
  meta_ofs << "proof_g1_size: " << proof.G1Size() << "\n";
  meta_ofs.close();

  std::cout << "\n========== Phase 3 Complete ==========\n";
  std::cout << "prove:             " << prove_ms << " ms\n";
  std::cout << "prove_total:       " << (trajectory_gen_ms + compute_com_ms + prove_ms) << " ms\n";
  std::cout << "peak_memory:       " << misc::GetPeakMemoryByPid(getpid()) / 1024.0 << " MB\n";
  std::cout << "======================================\n";
}

/**
 * Phase 4: Verify proof only.
 * Loads commitment and proof, verifies.
 */
inline void VerifyProofPhase(std::string const& input_dir = ".") {
  Tick tick(__FN__);

  // Load metadata
  int64_t num_instances = 0;
  {
    std::ifstream meta_ifs(input_dir + "/flappybird_meta.txt");
    std::string line;
    while (std::getline(meta_ifs, line)) {
      if (line.find("num_instances:") != std::string::npos) {
        num_instances = std::stoll(line.substr(line.find(":") + 1));
      }
    }
  }

  // Load copy ranges
  std::vector<argument::CopyRange> copy_ranges = LoadCopyRanges(input_dir + "/flappybird_copy_ranges.bin");

  // Create protoboard to get sparse matrices
  libsnark::protoboard<Fr> pb;
  DqnEnvGadgetVars vars;
  auto gadget_ptr = CreateDqnEnvGadget(pb, vars, "DqnEnvGadget");
  SparseMatrix sparse_a, sparse_b, sparse_c;
  circuit::PreprocessSparse(pb, sparse_a, sparse_b, sparse_c);

  // Load commitment
  argument::A12::CommitmentPub com_pub;
  {
    std::ifstream ifs(input_dir + "/flappybird_commitment.bin", std::ios::binary);
    ifs.seekg(0, std::ios::end);
    size_t size = ifs.tellg();
    ifs.seekg(0, std::ios::beg);
    std::vector<uint8_t> buf(size);
    ifs.read(reinterpret_cast<char*>(buf.data()), size);
    yas::mem_istream is(buf.data(), size);
    yas::binary_iarchive<yas::mem_istream, YasBinF()> ia(is);
    ia.serialize(com_pub);
    // Skip com_sec
    std::cout << "Loaded commitment from " << input_dir << "/flappybird_commitment.bin\n";
  }

  // Load proof and seed
  argument::A12::Proof proof;
  h256_t seed;
  {
    std::ifstream ifs(input_dir + "/flappybird_proof.bin", std::ios::binary);
    ifs.seekg(0, std::ios::end);
    size_t size = ifs.tellg();
    ifs.seekg(0, std::ios::beg);
    std::vector<uint8_t> buf(size);
    ifs.read(reinterpret_cast<char*>(buf.data()), size);
    yas::mem_istream is(buf.data(), size);
    yas::binary_iarchive<yas::mem_istream, YasBinF()> ia(is);
    ia.serialize(proof);
    ia.serialize(seed);
    std::cout << "Loaded proof from " << input_dir << "/flappybird_proof.bin\n";
  }

  // Verify
  auto verify_start = std::chrono::high_resolution_clock::now();
  argument::A12::SparseVerifyInput verify_input(
      sparse_a, sparse_b, sparse_c, com_pub, num_instances,
      copy_ranges, pc::kGetRefG1);
  bool verify_success = argument::A12::VerifyIf(proof, seed, verify_input);
  auto verify_end = std::chrono::high_resolution_clock::now();
  double verify_ms = std::chrono::duration<double, std::milli>(verify_end - verify_start).count();

  // Update metadata
  std::ofstream meta_ofs(input_dir + "/flappybird_meta.txt", std::ios::app);
  meta_ofs << "verify_ms: " << verify_ms << "\n";
  meta_ofs << "verify_success: " << (verify_success ? "true" : "false") << "\n";
  meta_ofs.close();

  std::cout << "\n========== Phase 4 Complete ==========\n";
  std::cout << "verify:            " << verify_ms << " ms\n";
  std::cout << "verify_success:    " << (verify_success ? "true" : "false") << "\n";
  std::cout << "peak_memory:       " << misc::GetPeakMemoryByPid(getpid()) / 1024.0 << " MB\n";
  std::cout << "======================================\n";

  CHECK(verify_success, "Verification failed!");
}

/**
 * Print final summary from metadata file.
 */
inline void PrintSummary(std::string const& input_dir = ".") {
  std::cout << "\n========== Final Summary ==========\n";
  std::ifstream meta_ifs(input_dir + "/flappybird_meta.txt");
  std::string line;
  while (std::getline(meta_ifs, line)) {
    std::cout << line << "\n";
  }
  std::cout << "===================================\n";
}

/**
 * Run the full iterated function R1CS proof using A12 protocol
 * for Flappy Bird DQN + Environment.
 */
inline void IteratedFunctionProof(size_t max_steps,
                                  std::string const& data_dir = "") {
  IteratedFunctionProofStats stats;
  auto total_start = std::chrono::high_resolution_clock::now();

  namespace fp = circuit::fp;
  fp::RationalConst<8, 24> rc;

  FlappyBird::Para para;
  FlappyBird::LoadPara(para, data_dir);

  // ========== 1. Create protoboard and gadget ==========
  libsnark::protoboard<Fr> pb;
  DqnEnvGadgetVars vars;
  auto gadget_ptr = CreateDqnEnvGadget(pb, vars, "DqnEnvGadget");
  auto& gadget = *gadget_ptr;

  SparseMatrix sparse_a, sparse_b, sparse_c;
  circuit::PreprocessSparse(pb, sparse_a, sparse_b, sparse_c);

  auto r1cs_stats = circuit::GetR1csStats(sparse_a, sparse_b, sparse_c);
  std::cout << "R1CS: " << r1cs_stats.num_constraints << " constraints, "
            << r1cs_stats.num_variables << " variables\n";

  // ========== 1.5 Separate DQN, Env, and Render constraint counting ==========
  {
    // DQN only protoboard
    libsnark::protoboard<Fr> pb_dqn;
    libsnark::pb_variable_array<Fr> dqn_image;
    dqn_image.allocate(pb_dqn, circuit::flappybird::DqnGadget<8, 24>::IMG_SIZE, "dqn_image");
    libsnark::pb_variable_array<Fr> dqn_conv1_w, dqn_conv2_w, dqn_conv3_w, dqn_fc1_w, dqn_fc2_w;
    dqn_conv1_w.allocate(pb_dqn, circuit::flappybird::DqnGadget<8, 24>::conv1_weight_size(), "dqn_conv1_w");
    dqn_conv2_w.allocate(pb_dqn, circuit::flappybird::DqnGadget<8, 24>::conv2_weight_size(), "dqn_conv2_w");
    dqn_conv3_w.allocate(pb_dqn, circuit::flappybird::DqnGadget<8, 24>::conv3_weight_size(), "dqn_conv3_w");
    dqn_fc1_w.allocate(pb_dqn, circuit::flappybird::DqnGadget<8, 24>::fc1_weight_size(), "dqn_fc1_w");
    dqn_fc2_w.allocate(pb_dqn, circuit::flappybird::DqnGadget<8, 24>::fc2_weight_size(), "dqn_fc2_w");
    circuit::flappybird::DqnGadget<8, 24> dqn_only(
        pb_dqn, dqn_image, dqn_conv1_w, dqn_conv2_w, dqn_conv3_w, dqn_fc1_w, dqn_fc2_w, "DqnOnly");
    size_t dqn_constraints = pb_dqn.num_constraints();
    size_t dqn_variables = pb_dqn.num_variables();

    // Env only protoboard
    libsnark::protoboard<Fr> pb_env;
    libsnark::pb_variable_array<Fr> env_in_state;
    env_in_state.allocate(pb_env, circuit::flappybird::EnvGadget::STATE_DIM, "env_in_state");
    libsnark::pb_variable<Fr> env_action;
    env_action.allocate(pb_env, "env_action");
    libsnark::pb_variable<Fr> env_next_gap_y;
    env_next_gap_y.allocate(pb_env, "env_next_gap_y");
    libsnark::linear_combination<Fr> env_action_lc(env_action);
    circuit::flappybird::EnvGadget env_only(
        pb_env, env_in_state, env_action_lc, env_next_gap_y, "EnvOnly");
    size_t env_constraints = pb_env.num_constraints();
    size_t env_variables = pb_env.num_variables();

    // Render only protoboard
    libsnark::protoboard<Fr> pb_render;
    libsnark::pb_variable_array<Fr> render_state;
    render_state.allocate(pb_render, 7, "render_state");  // RenderGadget uses state[0..6]
    circuit::flappybird::RenderGadget render_only(pb_render, render_state, "RenderOnly");
    size_t render_constraints = pb_render.num_constraints();
    size_t render_variables = pb_render.num_variables();

    // Print DQN, Env, and Render statistics
    std::cout << "\n========== Circuit Component Statistics ==========\n";
    std::cout << "DQN (Neural Network Inference):\n";
    std::cout << "  Constraints: " << dqn_constraints << "\n";
    std::cout << "  Variables:   " << dqn_variables << "\n";
    std::cout << "Env (State Transition):\n";
    std::cout << "  Constraints: " << env_constraints << "\n";
    std::cout << "  Variables:   " << env_variables << "\n";
    std::cout << "Render (Image Rendering):\n";
    std::cout << "  Constraints: " << render_constraints << "\n";
    std::cout << "  Variables:   " << render_variables << "\n";
    std::cout << "Total (DQN + Env + Render + packing):\n";
    std::cout << "  Constraints: " << (dqn_constraints + env_constraints + render_constraints) << " (plus packing constraints)\n";
    std::cout << "  Variables:   " << (dqn_variables + env_variables + render_variables) << " (plus shared variables)\n";
    std::cout << "==================================================\n\n";
  }

  int64_t num_constraints = r1cs_stats.num_constraints;
  // r1cs_stats.num_variables = mat_a.cols() = pb.num_variables() + 1 (includes "one" variable)
  // Use pb.num_variables() directly to avoid off-by-one confusion
  int64_t num_variables = static_cast<int64_t>(pb.num_variables());
  stats.num_constraints = num_constraints;
  stats.num_vars = num_variables;

  // Copy constraint indices
  // in_state and prev_images are allocated contiguously, out_state/out_image may not be
  size_t in_start_idx = vars.in_state[0].index;
  size_t out_start_idx = gadget.out_state()[0].index;
  size_t prev_images_start_idx = vars.prev_images[0].index;
  size_t out_image_start_idx = gadget.out_image()[0].index;
  constexpr int IMG_84 = 84 * 84;  // 7056 pixels per frame

  // ========== 2. Generate trajectory (directly into column-major layout) ==========
  auto traj_start = std::chrono::high_resolution_clock::now();
  int64_t total_vars = num_variables + 1;

  // Pre-allocate flat_row_z with max_steps columns to avoid row_z intermediate storage.
  // This eliminates the transpose phase and its 2x peak memory overhead.
  FlatMatrix flat_row_z(total_vars, static_cast<int64_t>(max_steps));
  size_t actual_steps = 0;

  // Assign CNN weights once
  AssignWeights(pb, vars.conv1_weights, para.conv1);
  AssignWeights(pb, vars.conv2_weights, para.conv2);
  AssignWeights(pb, vars.conv3_weights, para.conv3);
  AssignWeights(pb, vars.fc1_weights, para.fc1);
  AssignWeights(pb, vars.fc2_weights, para.fc2);

  // Initial state: bird at center, no velocity, pipes at right edge
  // gap_y range in Python: rng.randint(2,10)*10 + int(404/5) = 100~180
  std::vector<Fr> state = {
      Fr(244),   // bird_y = (512-24)/2 = 244 (center)
      Fr(0),     // bird_vy = 0
      Fr(288),   // pipe1_x = SCREEN_WIDTH
      Fr(140),   // pipe1_gap_y (within Python range 100~180)
      Fr(432),   // pipe2_x = SCREEN_WIDTH * 3/2
      Fr(160),   // pipe2_gap_y (within Python range 100~180)
      Fr(0),     // score = 0
      Fr(0)      // terminal = 0 (game not over)
  };

  // Previous 3 frames (initially all zeros)
  constexpr int PREV_IMAGES_SIZE = 3 * 84 * 84;
  std::vector<Fr> prev_images(PREV_IMAGES_SIZE, Fr(0));

#ifdef DEBUG
  // Game record for replay
  using json = nlohmann::json;
  json game_record;
  game_record["seed"] = 0;  // deterministic mode, no random seed
  game_record["initial_state"] = json::array();
  for (int i = 0; i < circuit::flappybird::EnvGadget::STATE_DIM; ++i) {
    game_record["initial_state"].push_back(state[i].getInt64());
  }
  game_record["steps"] = json::array();
#endif

  for (size_t step = 0; step < max_steps; ++step) {
    // Assign input state
    for (int i = 0; i < circuit::flappybird::EnvGadget::STATE_DIM; ++i) {
      pb.val(vars.in_state[i]) = state[i];
    }

    // Assign previous images (parallelized)
    auto assign_prev_images = [&](int64_t i) {
      pb.val(vars.prev_images[i]) = prev_images[i];
    };
    parallel::For(static_cast<int64_t>(PREV_IMAGES_SIZE), assign_prev_images);

    // Assign next_gap_y (deterministic, matching Python range: randint(2,10)*10 + 80)
    // Python range: 100~180. Use deterministic sequence within this range.
    int64_t next_gap_y_val = 100 + static_cast<int64_t>((step * 37 + 17) % 9) * 10;
    pb.val(vars.next_gap_y) = Fr(next_gap_y_val);

    // Run the full DQN + Env pipeline
    gadget.generate_r1cs_witness();

#ifdef DEBUG_CHECK_R1CS
    assert(pb.is_satisfied());
#endif

    // Write assignment directly into flat_row_z column (column-major layout).
    // This avoids allocating a separate row_z vector and the subsequent transpose.
    int64_t col_idx = static_cast<int64_t>(step);
    auto const& full_assignment = pb.full_variable_assignment();
    flat_row_z(0, col_idx) = FrOne();
    auto collect_assignment = [&](int64_t i) {
      flat_row_z(i + 1, col_idx) = full_assignment[i];
    };
    parallel::For(num_variables, collect_assignment);
    actual_steps = step + 1;

    // Read output state
    std::vector<Fr> out_state(circuit::flappybird::EnvGadget::STATE_DIM);
    for (int i = 0; i < circuit::flappybird::EnvGadget::STATE_DIM; ++i) {
      out_state[i] = pb.val(gadget.out_state()[i]);
    }

    int64_t in_by = state[0].getInt64();
    int64_t out_by = out_state[0].getInt64();
    int64_t in_vy = state[1].getInt64();
    int64_t out_vy = out_state[1].getInt64();

    int action = gadget.get_dqn_action_index();
    auto [q0, q1] = gadget.get_dqn_q_values();

#ifdef DEBUG
    std::cout << "Step " << step << ": bird_y=" << in_by
              << " vel=" << in_vy << " action=" << action
              << " -> bird_y=" << out_by << " vel=" << out_vy << "\n";

    // Record step for game replay
    {
      json step_record;
      step_record["step"] = step;
      step_record["state"] = json::array();
      for (int i = 0; i < circuit::flappybird::EnvGadget::STATE_DIM; ++i) {
        step_record["state"].push_back(state[i].getInt64());
      }
      step_record["dqn_action"] = action;
      step_record["next_gap_y"] = next_gap_y_val;
      step_record["next_state"] = json::array();
      for (int i = 0; i < circuit::flappybird::EnvGadget::STATE_DIM; ++i) {
        step_record["next_state"].push_back(out_state[i].getInt64());
      }
      step_record["is_terminal"] = is_terminal;
      game_record["steps"].push_back(step_record);
    }
#endif

    bool is_terminal = circuit::flappybird::EnvGadget::IsTerminal(out_state);

    // Update previous images: shift frames and add current rendered image
    // Must shift in order to avoid data race: frame0 reads frame1, frame1 reads frame2
    auto const& cur_image = gadget.out_image();
    constexpr int IMG_84 = 84 * 84;
    // Step 1: frame[0] = old frame[1] (safe: no concurrent write to frame1)
    auto copy_frame0 = [&](int64_t i) {
      prev_images[i] = prev_images[IMG_84 + i];
    };
    parallel::For(static_cast<int64_t>(IMG_84), copy_frame0);
    // Step 2: frame[1] = old frame[2] (safe: frame0 copy already done)
    auto copy_frame1 = [&](int64_t i) {
      prev_images[IMG_84 + i] = prev_images[2 * IMG_84 + i];
    };
    parallel::For(static_cast<int64_t>(IMG_84), copy_frame1);
    // Step 3: frame[2] = current rendered image
    auto copy_new_frame = [&](int64_t i) {
      prev_images[2 * IMG_84 + i] = pb.val(cur_image[i]);
    };
    parallel::For(static_cast<int64_t>(IMG_84), copy_new_frame);

    // Use output state as next input
    state = out_state;

    // Check terminal
    // if (is_terminal) {
    //   std::cout << "Terminal state reached at step " << step + 1 << "\n";
    //   break;
    // }
  }
  auto traj_end = std::chrono::high_resolution_clock::now();
  stats.trajectory_gen_ms =
      std::chrono::duration<double, std::milli>(traj_end - traj_start).count();

  stats.num_instances = actual_steps;
  std::cout << "Generated " << stats.num_instances << " valid steps.\n";

  // Shrink flat_row_z to actual number of steps if terminated early
  if (static_cast<int64_t>(actual_steps) < static_cast<int64_t>(max_steps)) {
    FlatMatrix trimmed(total_vars, static_cast<int64_t>(actual_steps));
    auto copy_col = [&](int64_t i) {
      for (int64_t j = 0; j < static_cast<int64_t>(actual_steps); ++j) {
        trimmed(i, j) = flat_row_z(i, j);
      }
    };
    parallel::For(total_vars, copy_col);
    flat_row_z = std::move(trimmed);
  }

#ifdef DEBUG
  // Save game record
  game_record["total_steps"] = stats.num_instances;
  game_record["final_state"] = json::array();
  for (int i = 0; i < circuit::flappybird::EnvGadget::STATE_DIM; ++i) {
    game_record["final_state"].push_back(state[i].getInt64());
  }
  {
    std::string record_path = "data/flappybird/dqn_env_game_record.json";
    std::ifstream test_dir("data/flappybird");
    if (!test_dir.is_open()) {
      record_path = "../data/flappybird/dqn_env_game_record.json";
    }
    std::ofstream record_file(record_path);
    if (record_file.is_open()) {
      record_file << game_record.dump(2);
      std::cout << "Game record saved to: " << record_path << "\n";
    } else {
      std::cerr << "Warning: could not save game record to " << record_path << "\n";
    }
  }
#endif
  CHECK(stats.num_instances >= 2, "Need at least 2 steps for A12 proof");

  // No separate transpose phase needed - data is already in column-major layout
  stats.matrix_transpose_ms = 0.0;

  // Build copy constraint ranges for step j -> step j+1:
  //   1. State copy: out_state[0..7] -> in_state[0..7]
  //   2. Frame shift: prev_images[frame1] -> prev_images[frame0]  (7056 pixels)
  //   3. Frame shift: prev_images[frame2] -> prev_images[frame1]  (7056 pixels)
  //   4. New frame:   out_image[0..7055] -> prev_images[frame2]   (7056 pixels)
  constexpr int STATE_DIM = circuit::flappybird::EnvGadget::STATE_DIM;
  int64_t prev_frame0_start = static_cast<int64_t>(prev_images_start_idx);
  int64_t prev_frame1_start = static_cast<int64_t>(prev_images_start_idx + IMG_84);
  int64_t prev_frame2_start = static_cast<int64_t>(prev_images_start_idx + 2 * IMG_84);

  std::vector<argument::CopyRange> copy_ranges;
  // CopyRange(l_a, l_b, l): A12 semantics is z_j[l_a..l_a+l-1] == z_{j+1}[l_b..l_b+l-1]
  // State: step j's out_state -> step j+1's in_state
  copy_ranges.emplace_back(
      static_cast<int64_t>(out_start_idx),
      static_cast<int64_t>(in_start_idx),
      static_cast<int64_t>(STATE_DIM));
  // Frame shift: step j's prev_images[frame1] -> step j+1's prev_images[frame0]
  copy_ranges.emplace_back(
      prev_frame1_start, prev_frame0_start, static_cast<int64_t>(IMG_84));
  // Frame shift: step j's prev_images[frame2] -> step j+1's prev_images[frame1]
  copy_ranges.emplace_back(
      prev_frame2_start, prev_frame1_start, static_cast<int64_t>(IMG_84));
  // New frame: step j's out_image -> step j+1's prev_images[frame2]
  copy_ranges.emplace_back(
      static_cast<int64_t>(out_image_start_idx),
      prev_frame2_start,
      static_cast<int64_t>(IMG_84));


#ifdef DEBUG
  // ========== 4a. Direct R1CS + Copy Constraint Verification (debug only) ==========
  {
    std::cout << "\n=== Verifying R1CS constraints (DEBUG) ===\n";
    bool all_satisfied = true;

    for (size_t j = 0; j < stats.num_instances; ++j) {
      std::vector<Fr> z_j = flat_row_z.col(static_cast<int64_t>(j));
      bool step_satisfied = true;
      int64_t violated_count = 0;

      // Use std::vector<int> to avoid std::vector<bool> bit-packing data race
      std::vector<int> constraint_results(num_constraints, 1);
      auto verify_constraint = [&](int64_t i) {
        Fr az = FrZero();
        for (int64_t k = sparse_a.row_ptr_[i]; k < sparse_a.row_ptr_[i + 1]; ++k)
          az += sparse_a.values_[k] * z_j[sparse_a.col_idx_[k]];
        Fr bz = FrZero();
        for (int64_t k = sparse_b.row_ptr_[i]; k < sparse_b.row_ptr_[i + 1]; ++k)
          bz += sparse_b.values_[k] * z_j[sparse_b.col_idx_[k]];
        Fr cz = FrZero();
        for (int64_t k = sparse_c.row_ptr_[i]; k < sparse_c.row_ptr_[i + 1]; ++k)
          cz += sparse_c.values_[k] * z_j[sparse_c.col_idx_[k]];
        constraint_results[i] = (az * bz == cz) ? 1 : 0;
      };
      parallel::For(num_constraints, verify_constraint);

      for (int64_t i = 0; i < num_constraints; ++i) {
        if (constraint_results[i] == 0) {
          step_satisfied = false;
          violated_count++;
          if (violated_count <= 5)
            std::cout << "  R1CS violation at step " << j << " constraint " << i << "\n";
        }
      }
      if (step_satisfied) {
        std::cout << "Step " << j << ": R1CS satisfied (" << num_constraints << " constraints)\n";
      } else {
        std::cout << "Step " << j << ": R1CS VIOLATED (" << violated_count
                  << " / " << num_constraints << " constraints failed)\n";
        all_satisfied = false;
      }
    }

    std::cout << "\n=== Verifying copy constraints (DEBUG) ===\n";
    std::string range_names[] = {"state", "prev_frame0<-frame1", "prev_frame1<-frame2", "prev_frame2<-out_image"};
    for (size_t j = 0; j + 1 < stats.num_instances; ++j) {
      bool copy_ok = true;
      for (size_t r = 0; r < copy_ranges.size(); ++r) {
        auto const& range = copy_ranges[r];
        int64_t violated = 0;
        for (int64_t k = 0; k < range.l; ++k) {
          Fr src_val = flat_row_z(range.l_a + k, static_cast<int64_t>(j));
          Fr dst_val = flat_row_z(range.l_b + k, static_cast<int64_t>(j + 1));
          if (src_val != dst_val) {
            violated++;
            if (violated <= 3)
              std::cout << "  Copy violated: step " << j << "->" << (j + 1)
                        << " range[" << range_names[r] << "] offset " << k << "\n";
            copy_ok = false;
            all_satisfied = false;
          }
        }
        if (violated > 0)
          std::cout << "  Range " << range_names[r] << ": " << violated
                    << " / " << range.l << " mismatches\n";
      }
      if (copy_ok)
        std::cout << "Step " << j << " -> " << (j + 1) << ": all copy constraints satisfied\n";
    }

    std::cout << "\nDirect Verify: " << (all_satisfied ? "PASS" : "FAIL") << "\n";
    CHECK(all_satisfied, "Direct R1CS + copy constraint verification failed");
  }
#endif

  // ========== 4b. A12 prove/verify ==========
  h256_t seed = misc::RandH256();
  argument::A12::SparseProveInput prove_input(
      sparse_a, sparse_b, sparse_c, flat_row_z, copy_ranges, pc::kGetRefG1);

  auto prove_total_start = std::chrono::high_resolution_clock::now();

  auto com_start = std::chrono::high_resolution_clock::now();
  argument::A12::CommitmentPub com_pub;
  argument::A12::CommitmentSec com_sec;
  argument::A12::ComputeCom(com_pub, com_sec, prove_input);
  auto com_end = std::chrono::high_resolution_clock::now();
  stats.compute_com_ms =
      std::chrono::duration<double, std::milli>(com_end - com_start).count();

  stats.com_g1_count = com_pub.com_z.size();

  auto prove_start = std::chrono::high_resolution_clock::now();
  argument::A12::Proof proof;
  argument::A12::ProveIf(proof, seed, prove_input, com_pub, com_sec);
  auto prove_end = std::chrono::high_resolution_clock::now();
  stats.prove_ms =
      std::chrono::duration<double, std::milli>(prove_end - prove_start).count();

  auto prove_total_end = std::chrono::high_resolution_clock::now();
  stats.prove_total_ms = stats.trajectory_gen_ms +
      std::chrono::duration<double, std::milli>(prove_total_end - prove_total_start).count();

  stats.proof_fr_size = proof.FrSize();
  stats.proof_g1_size = proof.G1Size();

  // Serialize commitment to get size
  yas::mem_ostream com_os;
  yas::binary_oarchive<yas::mem_ostream, YasBinF()> com_oa(com_os);
  com_oa.serialize(com_pub);
  stats.com_serialized_size = com_os.get_shared_buffer().size;

  // Serialize proof to get size
  yas::mem_ostream proof_os;
  yas::binary_oarchive<yas::mem_ostream, YasBinF()> proof_oa(proof_os);
  proof_oa.serialize(proof);
  stats.proof_serialized_size = proof_os.get_shared_buffer().size;

  stats.total_proof_size = stats.com_serialized_size + stats.proof_serialized_size;

  auto verify_total_start = std::chrono::high_resolution_clock::now();
  auto verify_start = std::chrono::high_resolution_clock::now();
  argument::A12::SparseVerifyInput verify_input(
      sparse_a, sparse_b, sparse_c, com_pub, stats.num_instances,
      copy_ranges, pc::kGetRefG1);
  stats.verify_success = argument::A12::VerifyIf(proof, seed, verify_input);
  auto verify_end = std::chrono::high_resolution_clock::now();
  stats.verify_ms =
      std::chrono::duration<double, std::milli>(verify_end - verify_start).count();
  auto verify_total_end = std::chrono::high_resolution_clock::now();
  stats.verify_total_ms =
      std::chrono::duration<double, std::milli>(verify_total_end - verify_total_start).count();

  auto total_end = std::chrono::high_resolution_clock::now();
  stats.total_ms =
      std::chrono::duration<double, std::milli>(total_end - total_start).count();

  stats.max_steps = max_steps;
  stats.peak_memory_mb = misc::GetPeakMemoryByPid(getpid()) / 1024.0;

  CHECK(stats.verify_success, "A12 verify failed");

  stats.print();
}

}  // namespace clink::flappybird
